### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by AlessandroAnnini** [the-software-factory/DartsTournament#1]
hi guys! great work!!
may i ask you to share the presentation you shown during the talk?
thanks_

**Comment by asprega** [comment]
Hi! Here are the slides:

https://docs.google.com/presentation/d/1AfmMSlg53j8Ut21iRmaW6r52eQsAXPKyKyt1X4ipWYE
https://docs.google.com/presentation/d/1wt-zGrcRObJEhR9Zlh5142PFis9yNikP6mRA4ZOl_nU

I'll add them to the README.md soon, and we'll also ask the professor to share them with all the students.

Thanks for asking!
